### ISSUE TITLE
not working when deployed in iis

### ISSUE THREAD

**Issue by rjonnalagadda** [gforceg/ts-clipboard#1]
this library works on localhost but does not copy any data when deployed on IIS. Any suggestions on how to overcome this?

**Comment by gforceg** [comment]
@rjonnalagadda,

What browser are you running?
Also, what sort of data are you trying to copy? Does it involve copying a file name on the client's machine?

One interesting I thing I found about this API is that [pop-ups must be enabled for the site](https://w3c.github.io/clipboard-apis/#allowed-to-modify-the-clipboard).

**Comment by rjonnalagadda** [comment]
Thanks for sharing the popup info, found out that the  clipboard js files were not properly deployed in the build, my mistake. I was copying 'URLs'. 
 Sorry :(

**Comment by gforceg** [comment]
No worries. Thanks for closing the issue.
